import discoverHtml from "./discoverHtml";
import Writer from "@sigitex/writer"

export function generateHtml() {
  const elements = discoverHtml()
  const ts = new Writer()

  return ts.line("// GENERATED BY @hypeup/generator")
    .line(`import type { ElementBuilder } from "@hypeup/runtime"`)
    .line()
    .line("declare global {")
    .indent()
    .each(elements, (element) => {
      ts.line(`/** ${element.help} */`)
        .line(`const ${element.jsName}: ElementBuilder`)
        .line()
    })
    .dedent()
    .line("}")
    .line()
    .emit()
}