import type { ElementSpec } from "./discoverHtml"
import type { SpecProperty, SpecAtrule } from "./discoverCss"
import Writer from "@sigitex/writer"

type PrimitivesInput = {
  elements: ElementSpec[]
  properties: SpecProperty[]
  atrules: SpecAtrule[]
}

export function generatePrimitives({ elements, properties, atrules }: PrimitivesInput) {
  const ts = new Writer()

  const tags = elements.filter(e => !e.isVoid)
  const voidTags = elements.filter(e => e.isVoid)

  ts.line("// GENERATED BY @hypeup/generator")
    .line()

  // htmlTags
  ts.line("export const htmlTags = [")
    .indent()
    .each(tags, (tag) => {
      ts.line(`"${tag.name}",`)
    })
    .dedent()
    .line("] as const")
    .line()

  // voidHtmlTags
  ts.line("export const voidHtmlTags = [")
    .indent()
    .each(voidTags, (tag) => {
      ts.line(`"${tag.name}",`)
    })
    .dedent()
    .line("] as const")
    .line()

  // atRules
  ts.line("export const atRules = {")
    .indent()
    .each(atrules, (atrule) => {
      ts.line(`$${atrule.jsName}: "@${atrule.name}",`)
    })
    .dedent()
    .line("} as const")
    .line()

  // cssProperties
  ts.line("export const cssProperties = {")
    .indent()
    .each(properties, (property) => {
      const keywords = property.values
        .filter(v => v.type === "keyword")
        .map(v => `"${v.name}"`)
      ts.line(`${property.jsName}: { cssName: "${property.name}", keywords: [${keywords.join(", ")}] },`)
    })
    .dedent()
    .line("} as const")
    .line()

  return ts.emit()
}
