import discoverHtml, { type ElementSpec } from "./discoverHtml"
import {
  discoverHtmlAttributes,
  type AttributeValueKind,
  type HtmlAttributeSpec,
} from "./discoverHtmlAttributes"
import Writer from "@sigitex/writer"

export function generateHtml() {
  const elements = discoverHtml()
  const attributes = discoverHtmlAttributes(elements.map((element) => element.name))
  const ts = new Writer()

  return ts.line("// GENERATED BY @hypeup/generator")
    .line(`import type {`)
    .indent()
    .line(`Attr,`)
    .line(`AtRule,`)
    .line(`CssClass,`)
    .line(`Each,`)
    .line(`Element,`)
    .line(`ElementBuilder,`)
    .line(`Lazy,`)
    .line(`Property,`)
    .line(`Raw,`)
    .line(`Rule,`)
    .dedent()
    .line(`} from "@hypeup/runtime"`)
    .line()
    .line("declare global {")
    .indent()
    .line("type AttributeValue = string | number | bigint")
    .line("type LooseString = string & {}")
    .line("type PrimitiveContent = string | number | bigint | boolean | null | undefined")
    .line("type NodeContent = Attr | AtRule | CssClass | Each<unknown> | Element | Lazy | Property | Raw | Rule")
    .line("type HtmlContent<Tag extends keyof AttributeMap> = PrimitiveContent | NodeContent | AttributeMap[Tag] | HtmlContent<Tag>[]")
    .line()
    .line("type GlobalAttributes = {")
    .indent()
    .each(attributes.globalAttributes, generateAttribute)
    .dedent()
    .line("}")
    .line()
    .each(elements, (element) => {
      ts.line(`type ${attributeTypeName(element)} = {`)
        .indent()
        .each(attributes.attributesByTag[element.name] ?? [], generateAttribute)
        .dedent()
        .line("}")
        .line()
    })
    .line("type AttributeMap = {")
    .indent()
    .each(elements, (element) => {
      ts.line(`${quoteKey(element.name)}: GlobalAttributes & ${attributeTypeName(element)}`)
    })
    .dedent()
    .line("}")
    .line()
    .each(elements, (element) => {
      ts.line(`/** ${element.help} */`)
        .line(`const ${element.jsName}: ElementBuilder<HtmlContent<${JSON.stringify(element.name)}>>`)
        .line()
    })
    .dedent()
    .line("}")
    .line()
    .emit()
}

function generateAttribute(attribute: HtmlAttributeSpec, ts: Writer) {
  ts.line(`/** ${escapeDoc(attribute.help)} */`)
    .line(`${quoteKey(attribute.name)}?: ${printValueType(attribute.value)}`)
}

function printValueType(kind: AttributeValueKind) {
  switch (kind.type) {
    case "boolean":
      return "boolean"
    case "number":
      return "number | `${number}`"
    case "enumerated": {
      const values = kind.values.map((value) => JSON.stringify(value))
      if (kind.loose) {
        values.push("LooseString")
      }
      return values.length > 0 ? values.join(" | ") : "AttributeValue"
    }
    case "string":
      return "AttributeValue"
  }
}

function attributeTypeName(element: ElementSpec) {
  return `${pascalCase(element.jsName)}Attributes`
}

function pascalCase(name: string) {
  return name.replace(/^_/, "").replace(/(^|-)([a-z0-9])/g, (_match, _separator, char: string) => char.toUpperCase())
}

function quoteKey(name: string) {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : JSON.stringify(name)
}

function escapeDoc(text: string) {
  return text.replace(/\*\//g, "*\\/")
}
