import discoverCss, { type SpecProperty, type SpecValue } from "./discoverCss"
import Writer from "@sigitex/writer"

const corePrimitives = new Set(["rule"])

export async function generateCss() {
  const { properties, colors, atrules } = await discoverCss()
  const ts = new Writer()

  return ts
    .line("// GENERATED BY @hypeup/generator")
    .line(`import type { Property, AtRule } from "@hypeup/runtime"`)
    .line()
    .line("type Content = any")
    .line()
    .line("type ColorKeywords = {")
    .indent()
    .each(colors, (color) => {
      ts.line(`${color}: Property`)
    })
    .dedent()
    .line("}")
    .line()
    .line("declare global {")
    .indent()
    .line("// Atrules")
    .line()
    .each(atrules, (atrule) => {
      const help = atrule.help ?? `@${atrule.name} atrule.`
      ts.line(`/** \`${help}\` */`)
        .line(`function $${atrule.jsName}(...contents: Content[]): AtRule`)
        .line()
    })
    .line("// Properties")
    .line()
    .each(properties.filter(p => !corePrimitives.has(p.jsName)), generateProperty)
    .dedent()
    .line("}")
    .line()
    .emit()
}

function generateProperty(property: SpecProperty, ts: Writer) {
  const specs = property.specs.map((s) => s.shortName).join(", ")
  const doc = `/** Create a \`${property.name}\` property. \`${specs}\` */`

  if (property.values.length === 0) {
    ts.line(doc)
      .line(`function ${property.jsName}(value: Content): Property`)
      .line()
    return
  }

  const keywords = property.values.filter((v) => v.type === "keyword")
  const hasColor = property.values.some((v) => v.type === "color")

  const mixins: string[] = []
  if (hasColor) {
    mixins.push("ColorKeywords")
  }

  ts.line(doc)
  ts.line(`const ${property.jsName}: {`)
    .indent()
    .line(`(value: Content): Property`)
    .each(keywords, (value) => {
      ts.line(`/** ${printValueHelp(value)} */`).line(
        `${value.jsName}: Property`,
      )
    })
    .dedent()

  if (mixins.length > 0) {
    ts.line(`} & ${mixins.join(" & ")}`)
  } else {
    ts.line(`}`)
  }
  ts.line()
}

function printValueHelp(value: SpecValue) {
  if (value.helps.length === 1) {
    return `${value.helps[0].help ?? "`" + value.name + "` keyword"}. \`${value.helps[0].spec.shortName}\``
  }
  return value.helps
    .map(
      (help) =>
        `\`${help.spec.shortName}\`: ${help.help ?? "`" + value.name + "` keyword."}`,
    )
    .join("\n\n    ")
}
